DjangoRightApp/testapp/urls.py
"""Defines URL patterns for testapp."""
from django.urls import path
from . import views

app_name = 'testapp'
urlpatterns = [
    path('', views.index, name="index"),
    # Page with a list of devices
    path("devices/", views.devices, name="devices"),
    path("values", views.ValueListView.as_view(), name="values"),
    path("variables", views.VariablesListView.as_view(), name="variables"),
    path("variables/<int:pk>/update", views.EditVariableView.as_view(), name="edit_variable"),
    # Page for adding a new device
    path("new_dev/", views.NewDevView.as_view(), name="new_dev"),
    # Page with a single device
    path("devices/<int:dev_id>/", views.device, name="device"),
    # Page for adding a new variable
    path("new_var/", views.NewVariableView.as_view(), name="new_var"),
    # Page for deleting a device
    path("devices/<int:pk>/delete", views.DelDeviceView.as_view(), name="del_dev"),
    # Page for deleting a variable
    path("variables/<int:pk>/delete", views.DelVariableView.as_view(), name="del_var"),

    path("devices/modbus/add", views.ModbusDeviceCreateView.as_view(), name="new_modbus_device")
]

DjangoRightApp/testproject/urls.py
from django.contrib import admin
from django.urls import path, include
from testapp.views import MyFileViewSet, MyDataViewSet, UsersViewSet
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

router = routers.DefaultRouter()

router.register(r'my-files', MyFileViewSet) 
router.register(r'my-data', MyDataViewSet) 
router.register(r'users', UsersViewSet) 

urlpatterns = [
    path('admin/', admin.site.urls),  
    path('', include("testapp.urls")),
    path('new-app/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoRightApp/testapp/models.py
from django.db import models
from datetime import datetime

# Create your models here.


## new file model

class MyFile(models.Model):
 file = models.FileField(blank=False, null=False,upload_to='docs/')
 description = models.CharField(null=True,max_length=255)
 uploaded_at = models.DateTimeField(auto_now_add=True)

def __str__(self):
    return self.description

## new file model


class AlembicVersion(models.Model):
    version_num = models.CharField(primary_key=True, max_length=255)
 
class Note(models.Model):
    note = models.CharField(blank=True, null=True, max_length=255)
    sec = models.IntegerField(blank=True, null=True)
    data = models.CharField(blank=True, null=True, max_length=255)
    date = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey('User', models.DO_NOTHING, blank=True, null=True)



class User(models.Model):
    email = models.CharField(blank=True, null=True, max_length=255)
    password = models.CharField(blank=True, null=True, max_length=255)
    first_name = models.CharField(blank=True, null=True, max_length=255)


    def __str__(self):
        return f"{self.first_name} ({self.email})"

class ModbusDevice(models.Model):
    name = models.CharField(max_length=100)
    ip = models.CharField(max_length=20)
    reg_first = models.IntegerField(blank=True, null=True)
    reg_amount = models.IntegerField(blank=True, null=True)
    date_updated = models.DateTimeField(blank=True, null=True)
    frequency = models.IntegerField(blank=True, null=True)
    enabled = models.BooleanField(blank=True, null=True)
    user = models.ForeignKey(to=User, on_delete=models.PROTECT, related_name="modbus_devices")

class ModbusDeviceValue(models.Model):
    device = models.ForeignKey(to=ModbusDevice, on_delete=models.PROTECT, related_name="values")
    date_updated = models.DateTimeField(auto_now=True)
    value = models.TextField()

DjangoRightApp/testapp/forms.py
from django.forms import ModelForm

from .models import Var, Device


class VariableForm(ModelForm):
    class Meta:
        model = Var
        exclude = ["date", "date_updated"]

class DeviceForm(ModelForm):
    class Meta:
        model = Device
        exclude = ["date"]

DjangoRightApp/testapp/views.py
from django.shortcuts import render, redirect


from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, DeleteView

from .forms import VariableForm, DeviceForm
from .models import Value, Var, Device, ModbusDevice, MyFile


from rest_framework.parsers import MultiPartParser, FormParser

from .models import MyFile, User, ModbusDevice
from .serializers import MyFileSerializer, ModbusDeviceSerializer, UserSerializer 

from rest_framework import generics
from rest_framework import viewsets
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.exceptions import NotFound
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.generics import get_object_or_404
# Create your views here.

def index(request):
    """The home page for Learning Log."""
    return render(request, 'testapp/index.html')

def devices(request):
    """Show all devices """
    devices = Device.objects.order_by('date')
    context = {'devices': devices}
    return render(request, 'testapp/devices.html', context)

def device(request, dev_id):
    """show a single device and all its variables"""
    device = Device.objects.get(id = dev_id)
    variables = device.var_set.order_by('user')
    context = {'device': device, 'variables': variables}
    return render(request, 'testapp/dev.html', context)

class ValueListView(ListView):
    template_name = "testapp/values.html"
    context_object_name = "values"
    model = Value
    def get_last(self):
        return Question.objects.order_by('date_created')[:5]

class VariablesListView(ListView):
    template_name = "testapp/variables.html"
    context_object_name = "variables"
    model = Var

## new views file added

class MyFileView(APIView):
    parser_classes = (MultiPartParser, FormParser)

    def post(self, request, *args, **kwargs):
        file_serializer = MyFileSerializer(data=request.data)
        if file_serializer.is_valid():
            file_serializer.save()
            return Response(file_serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(file_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, *args, **kwargs):
        files = MyFile.objects.all()
        file_serializer = MyFileSerializer(files, many=True)
        return Response(file_serializer.data, status=status.HTTP_200_OK)

    def get(self, request, file_id, *args, **kwargs):
        file_obj = get_object_or_404(MyFile, pk=file_id)
        file_serializer = MyFileSerializer(file_obj)
        return Response(file_serializer.data, status=status.HTTP_200_OK)

class MyFileViewSet(viewsets.ModelViewSet):
 queryset = MyFile.objects.all()
 serializer_class = MyFileSerializer

## new views file added

## new user view

 class MyDataView(APIView):
    parser_classes = (MultiPartParser, FormParser)

    def post(self, request, *args, **kwargs):
        data_serializer = ModbusDeviceSerializer(data=request.data)
        if data_serializer.is_valid():
            data_serializer.save()
            return Response(data_serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(data_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, *args, **kwargs):
        datas = ModbusDevice.objects.all()
        data_serializer = ModbusDeviceSerializer(datas, many=True)
        return Response(data_serializer.data, status=status.HTTP_200_OK)

    def get(self, request, data_id, *args, **kwargs):
        data_obj = get_object_or_404(ModbusDevice, pk=data_id)
        data_serializer = ModbusDeviceSerializer(data_obj)
        return Response(data_serializer.data, status=status.HTTP_200_OK)

## new user view

## new user view

class UsersView(APIView):
    parser_classes = (MultiPartParser, FormParser)

    def post(self, request, *args, **kwargs):
        data_serializer = UserSerializer(data=request.data)
        if data_serializer.is_valid():
            data_serializer.save()
            return Response(data_serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(data_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, *args, **kwargs):
        datas = User.objects.all()
        data_serializer = UserSerializer(datas, many=True)
        return Response(data_serializer.data, status=status.HTTP_200_OK)

    def get(self, request, data_id, *args, **kwargs):
        data_obj = get_object_or_404(User, pk=data_id)
        data_serializer = UserSerializer(data_obj)
        return Response(data_serializer.data, status=status.HTTP_200_OK)

class UsersViewSet(viewsets.ModelViewSet):
 queryset = User.objects.all()
 serializer_class = UserSerializer

## new user view

## new device view

 class MyDataView(APIView):
    parser_classes = (MultiPartParser, FormParser)

    def post(self, request, *args, **kwargs):
        data_serializer = ModbusDeviceSerializer(data=request.data)
        if data_serializer.is_valid():
            data_serializer.save()
            return Response(data_serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(data_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, *args, **kwargs):
        datas = ModbusDevice.objects.all()
        data_serializer = ModbusDeviceSerializer(datas, many=True)
        return Response(data_serializer.data, status=status.HTTP_200_OK)

    def get(self, request, data_id, *args, **kwargs):
        data_obj = get_object_or_404(ModbusDevice, pk=data_id)
        data_serializer = ModbusDeviceSerializer(data_obj)
        return Response(data_serializer.data, status=status.HTTP_200_OK)

class MyDataViewSet(viewsets.ModelViewSet):
 queryset = ModbusDevice.objects.all()
 serializer_class = ModbusDeviceSerializer


## new device view

class EditVariableView(UpdateView):
    template_name = "testapp/update_variable.html"
    success_url = reverse_lazy("testapp:variables")
    form_class = VariableForm
    model = Var

class NewVariableView(CreateView):
    template_name = "testapp/new_variable.html"
    success_url = reverse_lazy("testapp:variables")
    form_class = VariableForm
    model = Var

class NewDevView(CreateView):
    template_name = "testapp/new_dev.html"
    success_url = reverse_lazy("testapp:devices")
    form_class = DeviceForm
    model = Device

class DelDeviceView(DeleteView):
    template_name = "testapp/delete.html"
    success_url = reverse_lazy("testapp:devices")
    form_class = DeviceForm
    model = Device

class DelVariableView(DeleteView):
    template_name = "testapp/delete.html"
    success_url = reverse_lazy("testapp:variables")
    form_class = VariableForm
    model = Var


class ModbusDeviceCreateView(CreateView):
    model = ModbusDevice
    success_url = reverse_lazy("uzupelnic")
    template_name =  "testapp/new_modbus_device.html"
    fields = "__all__"

DjangoRightApp/testapp/templates/testapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
<!--Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">

          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="{% url 'testapp:devices' %}">Devices</a>
          <a class="nav-item nav-link" id="variables" href="{% url 'testapp:variables' %}">Variables</a>
          <a class="nav-item nav-link" id="variables" href="{% url 'testapp:values' %}">Show Data</a>

        </div>
      </div>
    </nav>
<p>
<a href="{% url 'testapp:index' %}">BE Conficurator</a>
</p>

    <div class="container">{% block content %} {% endblock %}</div>
<!--Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

DjangoRightApp/testapp/templates/testapp/delete.html
<form method="post">{% csrf_token %}

<p>Are you sure you want to delete "{{ object }}"?</p>

    <input type="submit" value="Confirm">
</form>

<div>
    <a href="{% url 'testapp:variables' %}">Go back</a>
</div>

DjangoRightApp/testapp/templates/testapp/dev.html
{% extends "testapp/base.html" %}
{% block content %}
<p>Device: {{ device }}</p>
<ul>
    {% for var in variables %}
    <li>
        <p>{{ var.date|date:'M d, Y H:i' }}</p>
        <p>{{ var.value_name|linebreaks }}</p>
    </li>
   {% empty %}
    <li>There are no variables for this device yet.</li>
    {% endfor %}
</ul>
{% endblock content %}

DjangoRightApp/testapp/templates/testapp/devices.html
{% extends "testapp/base.html" %}
{% block content %}
<p>Devices</p>
<ul>
   {% for device in devices %}
   <li>
   <a href="{% url 'testapp:device' device.id %}">{{ device }}</a>
   <a href="{% url 'testapp:del_dev' pk=device.id %}">Delete</a>
   </li>
   {% empty %}
   <li>No topics have been added yet.</li>
   {% endfor %}
</ul>
<a href="{% url 'testapp:new_dev' %}">Add a new device</a>

{% endblock content %}

DjangoRightApp/testapp/templates/testapp/index.html
{% extends "testapp/base.html" %}
{% block content %}
<p>Configurator</p>
<p> Configurator helps you keep track of your variables for a device that you created</p>
{% endblock content %}

DjangoRightApp/testapp/templates/testapp/new_dev.html
{% extends "testapp/base.html" %}
{% block content %}

<p>Add a new Device:</p>

<form action="{% url 'testapp:new_dev' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add device</button>
</form>
{% endblock content %}

DjangoRightApp/testapp/templates/testapp/new_modbus_device.html
{% extends "testapp/base.html" %}
{% block content %}

<p>Add a new Modbus Device:</p>

<form method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add device</button>
</form>
{% endblock content %}

DjangoRightApp/testapp/templates/testapp/new_variable.html
{% extends "testapp/base.html" %}
{% block content %}

<p>Add a new Variable:</p>

<form action="{% url 'testapp:new_var' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add Variable</button>
</form>
<div>
    <a href="{% url 'testapp:variables' %}">Cancel</a>
</div>
{% endblock content %}

DjangoRightApp/testapp/templates/testapp/notifications.html
{% extends "testapp/base.html" %}
{% block content %}
<p>Notifications</p>
<ul>
   {% for notification in notifications %}
   <li>
   <a>{{ notification.name }}</a>
   <a >Delete</a>
   </li>
   {% empty %}
   <li>No topics have been added yet.</li>
   {% endfor %}
</ul>
<a href="{% url 'testapp:new_dev' %}">Add a new device</a>

{% endblock content %}

DjangoRightApp/testapp/templates/testapp/update_variable.html
{% extends "testapp/base.html" %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Edit variable</title>
</head>
<body>

<form method="POST">
  {% csrf_token %}
          {% for field in form %}
            {{ field.label }}
            {{ field }}
            {% if not field.errors %}
                <p class="form-text-danger"></p>
            {% else %}
                {% for e in field.errors %}
                    <p class="form-text-danger">{{e}}</p>
                {% endfor %}
            {% endif %}
        {% endfor %}
  <button type="submit">Edit</button>
</form>

<br>
<div>
    <a href="{% url 'testapp:variables' %}">Go back</a>
</div>

</body>
{% endblock content %}

DjangoRightApp/testapp/templates/testapp/values.html
{% extends "testapp/base.html" %}
{% block content %}
<table style="width: 100%">
    <thead>
        <tr>
            <th>Date created</th>
            <th>Var</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        {% for value in values%}
            <tr>
                <td>{{value.date_created}}</td>
                <td>{{value.var.value_name}}</td>
                <td>{{value.value}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

DjangoRightApp/testapp/templates/testapp/variables.html
{% extends "testapp/base.html" %}
{% block content %}
<a href="{% url 'testapp:new_var' %}">Add a new variable</a>
<table style="width: 100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Date created</th>
            <th>User</th>
            <th>Device</th>
            <th>Date updated</th>
            <th>Frequency</th>
            <th>Enabled</th>
        </tr>
    </thead>
    <tbody>
        {% for variable in variables %}
            <tr>
                <td><a href="{% url 'testapp:edit_variable' pk=variable.id %}">{{variable.value_name }}</a></td>
                <td>{{variable.date  }}</td>
                <td>{{variable.user.email   }}</td>
                <td>{{variable.device.device_name    }}</td>
                <td>{{variable.date_updated     }}</td>
                <td>{{variable.frequency      }}</td>
                <td>{{variable.enabled       }}</td>
                <td><a href="{% url 'testapp:del_var' pk=variable.id %}">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}